import {useMemo,useState,type ReactNode} from 'react';
import {Search,Github,ArrowUpRight} from 'lucide-react';
import {PageHeading} from './controls';
import {GITHUB_URL} from '@/lib/quantek/data';
import {DBC_PROGRAM_ID} from '@/lib/quantek/dbc';
import {DOMAINS} from '@/lib/quantek/pq';

type Doc={id:string;title:string;group:string;body:ReactNode;text:string};
const code=(s:string)=><pre className="code-block">{s}</pre>;
const D=(id:string,title:string,group:string,paras:string[],extra?:string):Doc=>({id,title,group,text:(title+' '+paras.join(' ')+' '+(extra??'')).toLowerCase(),body:<>{paras.map((p,i)=>p.startsWith('- ')?<ul key={i}>{p.split('\n').map(l=><li key={l}>{l.replace(/^- /,'')}</li>)}</ul>:<p key={i}>{p}</p>)}{extra&&code(extra)}</>});
export const DOCS:Doc[]=[
D('overview','Overview','Foundations',['QUANTEK is a launch and liquidity operations console for Meteora Dynamic Bonding Curve pools on Solana, with an optional hash-based provenance layer.','Two halves: the Console (agent, pools, positions, fees, activity) and the Product (launch, identity, Quantum Wallets, verification, docs). Every chain write passes through one review model and is signed by your wallet in the browser.']),
D('threat-model','Threat Model','Foundations',['- Adversary may hold a large quantum computer able to break ed25519 and ECDSA.\n- Adversary controls the network and may serve forged metadata.\n- QUANTEK servers are not trusted with secrets — none exist in this build.\n- Users may reuse a one-time key by mistake; the ledger must refuse.','Out of scope: compromise of the device running the browser, and protection of ordinary Solana balances (see Security Boundaries).']),
D('primitives','Cryptographic Primitives','Cryptography',['SHA-256 is the only hash. HKDF-SHA256 expands seeds; scrypt hardens optional passphrases. Every hash call is domain-separated with a QUANTEK namespace string.'],Object.values(DOMAINS).join('\n')),
D('wots','WOTS-16','Cryptography',['A Winternitz one-time signature with w=16. A 32-byte digest yields 64 base-16 digits; a 3-digit checksum prevents forgeries that only advance chains, for 67 chains in total.','Signing reveals each chain at position d_i; verifying finishes the remaining 15−d_i steps and recovers the public key.'],'digits   = base16(H(domain ‖ 0x00 ‖ msg))           // 64\nchecksum = Σ (15 − d_i) → 3 base16 digits          // 67 total\nsig_i    = F^{d_i}(sk_i)\npk_i     = F^{15−d_i}(sig_i)\nF(x)     = SHA-256(proofDomain ‖ pubSeed ‖ leaf ‖ i ‖ j ‖ x)'),
D('merkle','Merkle Identity','Cryptography',['256 WOTS public keys are hashed into leaves and combined into a binary tree of height 8. The root, together with the public seed, is the identity. A signature carries its leaf index and 8 sibling nodes.'],'size = 4 (leaf) + 67×32 (chains) + 8×32 (path) = 2,404 bytes'),
D('derivation','Derivation & Hardening','Identity',['Your wallet signs a fixed, human-readable QUANTEK message. The signature never leaves the tab: it is hashed, optionally hardened with scrypt (N=2^15, r=8, p=1), then expanded with HKDF-SHA256 into a secret seed and a public seed.','Determinism means the same wallet + passphrase re-derives the same identity on any device. Losing the passphrase loses the identity.'],`ikm  = SHA-256(walletSig)\nikm  = scrypt(pass, "${DOMAINS.identity}" ‖ ikm, N=2^15, r=8, p=1)\nokm  = HKDF-SHA256(ikm, salt="${DOMAINS.identity}", info="qtk-seed", 64)\naddr = "qtk1" ‖ base32(H(domain, root, pubSeed)[..20]) ‖ check`),
D('registration','Registration','Identity',['Registration binds a Solana wallet to a qtk1 address with dual authorization: the wallet signed the derivation message, and leaf #0 signs the binding. In this build the result is a Local Registration Profile; no server ledger exists.']),
D('anchor','Solana Anchor','Identity',['An anchor publishes your root as an SPL Memo, giving it a public timestamp. It goes through prepare → review → simulate → wallet sign. An anchor exists only after confirmation is observed on-chain.'],'quantek:v1:identity:<qtk1-address>:<root>'),
D('standard-launch','Standard Launch','Launch',['A Meteora DBC launch: config, curve, fees, DAMM v2 migration, quote market and optional first buy. No attestation is attached.']),
D('quantum-launch','Quantum Launch','Launch',['A Standard Launch plus an Attestation Seal. The canonical launch description is hashed under the launch domain and signed by the next unused identity leaf. The seal is placed in token metadata extensions so anyone can verify it offline.'],`metadata.extensions["${DOMAINS.launch}"] = {\n  scheme, identity, root, publicSeed, launchDigest, proof\n}`),
D('schemes','Signature Schemes','Launch',['- QUANTEK Root — WOTS-16 + Merkle h=8. One-time, 2,404 B. Root of trust; reference implementation wired.\n- ML-DSA-65 (FIPS 204) — many-time lattice scheme; to be certified by a WOTS leaf. Implementation pending.\n- SLH-DSA-SHA2-128s (FIPS 205) — stateless hash-based; certified by a WOTS leaf. Implementation pending.\n- FN-DSA / Falcon-512 — experimental; not a final FIPS standard.\n- Hybrid ed25519 + ML-DSA-65 — advanced experimental.']),
D('possession','Proof of Possession','Identity',['A challenge-response: a random nonce is bound to your address, root and leaf index, then signed by one fresh leaf. The verifier recomputes the root. Each proof consumes a leaf permanently.']),
D('quantum-wallets','Quantum Wallets','Custody',['A vault chain where each vault is controlled by one WOTS key. A spend commits to recipient, mint, amount, next-vault hash and the program/version namespace; the remainder rolls to the next vault and the spent vault becomes a tombstone.','Signatures are staged in chunks because they exceed a single packet. QUANTEK has not deployed a verifier program; the feature is readiness-only.']),
D('dbc','Meteora DBC','Protocol',['QUANTEK uses @meteora-ag/dynamic-bonding-curve-sdk 1.5.13. New configs always migrate to DAMM v2 (MigrationOption.MET_DAMM_V2); DAMM v1 is not offered.','- partner.createConfig / createConfigAndPoolWithFirstBuy\n- creator.createPool / createPoolWithFirstBuy / createPoolWithPartnerAndCreatorFirstBuy\n- state.getPool / getPoolConfig / progress / fee metrics\n- migration.migrateToDammV2 · partner/creator fee claims'],`program: ${DBC_PROGRAM_ID}`),
D('tokenized-quotes','Tokenized Market Quotes','Protocol',['PoolConfig accepts any quote mint and, since SDK 1.5.13, any decimals. QUANTEK ships a 61-asset xStocks snapshot and accepts additional mints such as Ondo Global Markets assets after RPC validation.','Mints outside the permissionless set may need a DBC token badge passed as a remaining account (SDK 1.5.12+). Availability and transfer restrictions depend on the issuer and jurisdiction.']),
D('review-model','Transaction Review Model','Security',['- SDK builds an unsigned transaction.\n- QUANTEK assigns fee payer and recent blockhash, then freezes the message bytes.\n- Simulation runs without replacing the blockhash.\n- Genesis hash, fee payer, validity height and bytes are re-checked.\n- The wallet signs; returned bytes must match the reviewed message exactly.\n- Submission is a separate explicit step.']),
D('boundaries','Security Boundaries','Security',['Hash-based provenance proves who launched or attested something. It does not make ordinary Solana funds quantum-safe: ed25519 still authorizes every normal account. Quantum-protected custody requires a dedicated on-chain WOTS verifier vault, which QUANTEK has not deployed.','The demo identity uses a published secret and is labeled everywhere. Secrets and passphrases are never persisted; only consumed leaf indexes and public metadata are stored.']),
D('parameters','Parameters','Reference',[''],`w = 16          n = 32 B        chains = 67\nheight = 8      leaves = 256    signature = 2,404 B\nscrypt N=2^15 r=8 p=1           HKDF-SHA256\nprefix = qtk1\n${Object.entries(DOMAINS).map(([k,v])=>`${k.padEnd(14)} ${v}`).join('\n')}`),
D('examples','Verification Examples','Reference',['Open Verify, pick a category and load the valid or tampered demo. The tampered example changes one character of the message; the recomputed root diverges at the first chain and the result is Invalid.'],'{ "kind": "quantek-wots16-merkle-v1", "domain": "quantek.network/proof/v1",\n  "leaf": 7, "publicSeed": "…", "root": "…",\n  "signature": [67 × 32-byte hex], "authPath": [8 × 32-byte hex] }'),
];

export function DocsPage(){const[q,setQ]=useState('');const[active,setActive]=useState('overview');const list=useMemo(()=>{const s=q.trim().toLowerCase();return s?DOCS.filter(d=>d.text.includes(s)):DOCS},[q]);
const go=(id:string)=>{setActive(id);document.getElementById(`doc-${id}`)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};
return <><PageHeading eyebrow="DOCS / TECHNICAL REFERENCE" title="QUANTEK Documentation" description="Protocol model, cryptography, launch mechanics and security boundaries." action={<a className="protocol-badge" href={GITHUB_URL} target="_blank" rel="noopener noreferrer"><Github size={12}/>quantekdbc/quantek<ArrowUpRight size={10}/></a>}/>
<div className="search-field mb-6" style={{maxWidth:520}}><Search/><input aria-label="Search documentation" placeholder="Search documentation…" value={q} onChange={e=>setQ(e.target.value)}/></div>
<div className="docs-mobile"><select aria-label="Jump to section" value={active} onChange={e=>go(e.target.value)}>{list.map(d=><option key={d.id} value={d.id}>{d.group} · {d.title}</option>)}</select></div>
<div className="docs-layout"><nav className="docs-index" aria-label="Documentation sections">{list.map(d=><a key={d.id} href={`#doc-${d.id}`} className={active===d.id?'active':''} onClick={e=>{e.preventDefault();go(d.id)}}>{d.title}</a>)}<a href={`${GITHUB_URL}/tree/main/docs`} target="_blank" rel="noopener noreferrer">Repository docs ↗</a></nav>
<article className="docs-article">{list.length?list.map(d=><section key={d.id} id={`doc-${d.id}`} aria-labelledby={`h-${d.id}`}><div className="eyebrow">{d.group.toUpperCase()}</div><h2 id={`h-${d.id}`}>{d.title}</h2>{d.body}</section>):<div className="empty-state" role="status">No sections match “{q}”.</div>}<section><p>Source, issues and repository documentation: <a className="underline" href={GITHUB_URL} target="_blank" rel="noopener noreferrer">{GITHUB_URL}</a> · <a className="underline" href={`${GITHUB_URL}/blob/main/README.md`} target="_blank" rel="noopener noreferrer">README</a> · <a className="underline" href={`${GITHUB_URL}/blob/main/AGENTS.md`} target="_blank" rel="noopener noreferrer">AGENTS.md</a></p></section></article></div></>}