import {useState} from 'react';
import {ArrowLeft,ArrowRight,Code2,Rocket,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {PageHeading,Panel,Field} from './controls';
import {launchSchema} from '@/lib/quantek/validation';
import {useConsole} from '@/lib/quantek/context';
import {DBC_PROGRAM_ID,DEFAULT_MIGRATION} from '@/lib/quantek/dbc';
const initial={name:'',symbol:'',image:'',metadata:'',decimals:9,supply:1000000000,tokenType:'SPL' as const,builder:'Market Cap' as 'Market Cap'|'Two Segments'|'Liquidity Weights'|'Custom',initialCap:10000,migrationCap:100000,quoteThreshold:800,supplyMigration:80,startingBps:200,endingBps:50,scheduler:'Linear' as 'Linear'|'Exponential'|'Fixed',dynamic:true,collectMode:'Quote only' as 'Quote only'|'Both tokens',creatorFee:20,creationFee:0,partnerLiquidity:20,creatorLiquidity:80,locked:50,vesting:90,quote:'SOL' as 'SOL'|'USDC'|'Custom',customMint:''};
export function LaunchPage(){const[step,setStep]=useState(0);const[d,setD]=useState(initial);const[error,setError]=useState('');const[json,setJson]=useState(false);const c=useConsole();const steps=['Token','Curve','Fees','Migration','Quote','Review'];
function update(key:keyof typeof d,value:string|number|boolean){setD(v=>({...v,[key]:value}))}
function field(key:keyof typeof d,label:string,type='number',hint?:string){return <Field label={label} hint={hint}><input type={type} step={type==='number'?'any':undefined} maxLength={type==='text'?2048:undefined} value={String(d[key])} onChange={e=>update(key,type==='number'?(isNaN(e.target.valueAsNumber)?0:e.target.valueAsNumber):e.target.value)}/></Field>}
function next(){const parsed=launchSchema.safeParse(d);const keys=[['name','symbol','image','metadata','decimals','supply','tokenType'],['builder','initialCap','migrationCap','quoteThreshold','supplyMigration'],['startingBps','endingBps','scheduler','creatorFee','creationFee'],['partnerLiquidity','creatorLiquidity','locked','vesting'],['quote','customMint']][step];const issue=!parsed.success?parsed.error.issues.find(i=>keys?.includes(String(i.path[0]))):undefined;if(issue){setError(issue.message);return}setError('');setStep(s=>Math.min(5,s+1))}
function review(){const r=launchSchema.safeParse(d);if(!r.success){setError(r.error.issues[0]?.message??'Invalid launch draft.');return}c.setPlan({title:`${d.symbol} · DBC Launch Plan`,steps:[`Validate ${d.name} metadata and ${d.supply.toLocaleString()} token supply.`,`Build reusable PoolConfig with ${d.startingBps} → ${d.endingBps} bps fees; derived SDK curve required.`,`Wallet checkpoint 1: partner.createConfig with MET_DAMM_V2.`,`Wallet checkpoint 2: creator.createPool with ${d.quote} quote mint; mint signer required.`,`Monitor quote reserve until ${d.quoteThreshold} ${d.quote}; migrate to DAMM v2 after threshold.`],accounts:['New config keypair (not generated)','New token mint keypair (not generated)','Creator wallet',`${d.quote} quote mint`,DBC_PROGRAM_ID],fee:'RPC estimate required + rent',signatures:2});c.log(`${d.symbol} launch review generated`,'Launch')}
const summary={...d,migrationOption:DEFAULT_MIGRATION,migrationTarget:'MET_DAMM_V2',programId:DBC_PROGRAM_ID,status:'simulation-draft',curveStatus:'SDK derivation pending'};
return <><PageHeading eyebrow="PRIMARY MARKET / METEORA DBC" title="Launch with DBC" description="Define the token, curve and migration policy. Review every account before wallet signing."/><div className="notice mb-6"><ShieldCheck size={16}/>Simulation draft. No config or pool will be created. A deployable curve, account addresses and wallet review are required for live launch.</div><div className="wizard-steps">{steps.map((s,i)=><Button key={s} variant="ghost" disabled={i>step} className={step===i?'current':''} onClick={()=>{setStep(i);setError('')}}><span>{String(i+1).padStart(2,'0')}</span>{s}</Button>)}</div><div className="wizard-layout"><section className="instrument"><div className="wizard-form"><h2>{String(step+1).padStart(2,'0')} / {steps[step]} configuration</h2><div className="form-grid">
{step===0&&<>{field('name','Token name','text')}{field('symbol','Symbol','text')}{field('image','Image URI','text','HTTPS or IPFS. No upload or remote fetch in demo.')}{field('metadata','Metadata URI','text')}{field('decimals','Decimals (0–9)')}{field('supply','Total supply')}<Field label="Token standard"><select value={d.tokenType} onChange={e=>update('tokenType',e.target.value)}><option>SPL</option><option>Token-2022</option></select></Field></>}
{step===1&&<><Field label="Curve builder"><select value={d.builder} onChange={e=>update('builder',e.target.value)}>{['Market Cap','Two Segments','Liquidity Weights','Custom'].map(x=><option key={x}>{x}</option>)}</select></Field>{field('initialCap','Initial market cap (USD)')}{field('migrationCap','Migration market cap (USD)')}{field('quoteThreshold',`Migration quote threshold (${d.quote})`)}{field('supplyMigration','Supply on migration (%)')}<div className="notice">{d.builder==='Custom'?'Custom curve points must be supplied and validated through the SDK before deployment.':`${d.builder} draft. Curve segment derivation is not executed in this preview.`}</div></>}
{step===2&&<>{field('startingBps','Starting fee (bps)')}{field('endingBps','Ending fee (bps)')}<Field label="Fee scheduler"><select value={d.scheduler} onChange={e=>update('scheduler',e.target.value)}>{['Linear','Exponential','Fixed'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Collect-fee mode"><select value={d.collectMode} onChange={e=>update('collectMode',e.target.value)}><option>Quote only</option><option>Both tokens</option></select></Field>{field('creatorFee','Creator trading fee share (%)')}{field('creationFee','Pool creation fee (SOL)')}<div className="module-row"><span>Dynamic fee</span><Switch aria-label="Dynamic fee" checked={d.dynamic} onCheckedChange={v=>update('dynamic',v)}/></div></>}
{step===3&&<><Field label="Migration target"><input readOnly value="MET_DAMM_V2 · DAMM v2"/></Field>{field('partnerLiquidity','Partner liquidity (%)')}{field('creatorLiquidity','Creator liquidity (%)')}{field('locked','Permanently locked liquidity (%)')}{field('vesting','Vesting duration (days)')}<div className="notice">Partner and creator shares must total 100%. Permanent locks cannot be undone after deployment.</div></>}
{step===4&&<><Field label="Quote token"><select value={d.quote} onChange={e=>update('quote',e.target.value)}>{['SOL','USDC','Custom'].map(x=><option key={x}>{x}</option>)}</select></Field>{d.quote==='Custom'?field('customMint','Custom quote mint','text'):<Field label="Quote mint"><input readOnly value={d.quote==='SOL'?'So11111111111111111111111111111111111111112':'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'}/></Field>}<div className="notice">Quote mint decimals and token program must be verified against the active network before config creation.</div></>}
{step===5&&<><Field label="Token"><input readOnly value={`${d.name} (${d.symbol})`}/></Field><Field label="Supply"><input readOnly value={`${d.supply.toLocaleString()} · ${d.decimals} decimals`}/></Field><Field label="Migration"><input readOnly value={`${d.quoteThreshold} ${d.quote} → DAMM v2`}/></Field><Field label="Fee schedule"><input readOnly value={`${d.startingBps} → ${d.endingBps} bps · ${d.scheduler}`}/></Field><div className="notice">Config / pool addresses: not generated. This is a design draft, not an unsigned deployable transaction.</div></>}
</div>{error&&<div className="error-message" role="alert">{error}</div>}<div className="form-actions"><Button variant="outline" disabled={step===0} onClick={()=>{setStep(s=>s-1);setError('')}}><ArrowLeft/>Back</Button><span className="micro">{step+1} OF 6</span>{step<5?<Button onClick={next}>Continue<ArrowRight/></Button>:<Button onClick={review}><Rocket/>Review transaction plan</Button>}</div><Button className="json-toggle mt-4" variant="ghost" onClick={()=>setJson(v=>!v)}><Code2/>{json?'Hide':'Show'} advanced JSON draft</Button>{json&&<pre className="code-block">{JSON.stringify(summary,null,2)}</pre>}</div></section><Panel title="Launch manifest" tag="DRAFT" className="wizard-summary"><div className="detail-rows"><div><span>Token</span><strong>{d.symbol||'Not defined'}</strong></div><div><span>Standard</span><strong>{d.tokenType}</strong></div><div><span>Builder</span><strong>{d.builder}</strong></div><div><span>Quote</span><strong>{d.quote}</strong></div><div><span>Migration</span><strong>DAMM v2</strong></div><div><span>Network</span><strong>{c.network}</strong></div><div><span>Wallet</span><strong>{c.account?'Connected':'Not connected'}</strong></div></div><div className="notice">No wallet signatures requested during configuration. Live transactions are never fabricated.</div></Panel></div></>}