import {Link,useRouterState} from '@tanstack/react-router';
import {useEffect,useState,type ReactNode} from 'react';
import {LayoutDashboard,Orbit,Rocket,Layers3,ChartNoAxesCombined,Coins,Fingerprint,ScanLine,ListFilter,Settings,Wallet,LoaderCircle,ChevronDown,Command,ArrowUpRight,Menu,X,ChevronRight,Globe,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Geometry,Wordmark} from './geometry';
import {navigation} from '@/lib/quantek/data';
import {useConsole} from '@/lib/quantek/context';
const icons=[LayoutDashboard,Orbit,Rocket,Layers3,ChartNoAxesCombined,Coins,Fingerprint,ScanLine,ListFilter,Settings];
export function Shell({children}:{children:ReactNode}){const path=useRouterState({select:s=>s.location.pathname});const c=useConsole();const[walletOpen,setWalletOpen]=useState(false);const[palette,setPalette]=useState(false);const[mobile,setMobile]=useState(false);const[search,setSearch]=useState('');const title=navigation.find(n=>n[1]===path)?.[0]??'Console';
useEffect(()=>{function onKey(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setPalette(p=>!p)}}document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[]);
const nav=(isMobile=false)=>navigation.map(([label,to],i)=>{const Icon=icons[i]??LayoutDashboard;return <Link to={to} key={to} className={isMobile?'':`nav-link ${path===to?'active':''}`} onClick={()=>setMobile(false)} aria-current={path===to?'page':undefined}><Icon aria-hidden="true"/>{label}{label==='Pools'&&<span className="nav-count">03</span>}{label==='Activity'&&<span className="nav-count">{String(c.events.length).padStart(2,'0')}</span>}</Link>});
return <div className="app-shell"><a href="#workspace-content" className="skip-link">Skip to QUANTEK workspace</a><header className="topbar"><Link to="/" className="brand" aria-label="QUANTEK Home"><Geometry compact/><Wordmark/></Link><div className="topbar-right"><Button variant="ghost" className="network-button" onClick={()=>{const n=c.network==='devnet'?'mainnet-beta':'devnet';c.setNetwork(n);c.setRpc(n==='devnet'?'https://api.devnet.solana.com':'https://api.mainnet-beta.solana.com')}} aria-label={`Switch to ${c.network==='devnet'?'Mainnet':'Devnet'}`}><span className="live-dot"/>{c.network==='devnet'?'Devnet':'Mainnet'}<ChevronDown size={11}/></Button><div className="rpc-status" aria-live="polite">RPC <span className="live-dot"/>{c.rpcHealth}</div><Button variant="ghost" className="command-trigger" onClick={()=>setPalette(true)} aria-label="Open command palette"><Command size={13}/><span className="keycap">⌘ K</span></Button><Button className="top-wallet" variant="outline" onClick={()=>setWalletOpen(true)}><Wallet aria-hidden="true"/>{c.account?`${c.account.address.slice(0,4)}…${c.account.address.slice(-4)}`:'Connect Wallet'}</Button></div></header><aside className="sidebar"><div className="rail-label">WORKSPACE / 01</div><nav aria-label="Main Navigation">{nav().slice(0,6)}<div className="nav-divider" role="separator"/>{nav().slice(6,9)}</nav><div className="rail-bottom">{nav().slice(9)}<div className="rail-system"><div className="micro"><span className="live-dot"/>SIMULATION ENVIRONMENT</div><p>No live funds at risk.</p><Link to="/settings" className="micro flex justify-between mt-4">NETWORK SETTINGS<ArrowUpRight size={12}/></Link></div><div className="rail-footer"><span>QUANTEK v0.1</span><span>α</span></div></div></aside><main className="workspace"><div className="workspace-top"><div className="breadcrumb" aria-label="Breadcrumb"><Button variant="ghost" size="icon" className="mobile-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu/></Button><Globe size={12} aria-hidden="true"/><span>Workspace</span><ChevronRight size={10} aria-hidden="true"/><span className="text-foreground">{title}</span></div><div className="flex items-center gap-4"><span className="workspace-date">SESSION / SIMULATED</span><span className="status-tag" aria-label="Status: Demo Mode"><span className="live-dot"/>DEMO MODE</span></div></div><div className="page-content" id="workspace-content" tabIndex={-1}>{children}<footer className="footer"><span><ShieldCheck size={10} aria-hidden="true"/>NON-CUSTODIAL BY DESIGN · WALLET-CONTROLLED EXECUTION</span><span>WOTS-16 / SHA-256 · SOLANA / METEORA DBC <ArrowUpRight size={10} aria-hidden="true"/></span></footer></div></main>
<Dialog open={walletOpen} onOpenChange={setWalletOpen}><DialogContent><DialogTitle>{c.account?'Connected wallet':'Connect a wallet'}</DialogTitle><DialogDescription>Wallet-standard connection. QUANTEK never asks for private keys.</DialogDescription>{c.account?<><div className="code-block">{c.account.address}</div><Button disabled={c.walletBusy} variant="outline" onClick={async()=>{await c.disconnect();setWalletOpen(false)}}>Disconnect wallet</Button></>:<div className="wallet-list">{c.wallets.length?c.wallets.map(w=><Button disabled={c.walletBusy} variant="outline" key={w.name} onClick={async()=>{if(await c.connect(w))setWalletOpen(false)}}>{c.walletBusy&&<LoaderCircle className="animate-spin"/>}<img src={w.icon} alt=""/>{w.name}<ArrowUpRight className="ml-auto" aria-hidden="true"/></Button>):<div className="empty-state"><Wallet size={28} aria-hidden="true"/>No compatible browser wallet detected.<p>Install Phantom or Solflare, then reopen this dialog.</p></div>}</div>}{c.walletError&&<div role="alert" className="error-message">{c.walletError}</div>}<div className="notice">Demo pools remain simulated after connection. Connecting alone does not authorize transactions.</div></DialogContent></Dialog>
<Dialog open={palette} onOpenChange={setPalette}><DialogContent><DialogTitle>Command center</DialogTitle><DialogDescription>QUANTEK workspace</DialogDescription><input autoFocus aria-label="Search pages" placeholder="Search pages…" value={search} onChange={e=>setSearch(e.target.value)}/>{!navigation.some(n=>n[0].toLowerCase().includes(search.toLowerCase()))&&<div className="empty-state" role="status">No matching QUANTEK pages.</div>}<div className="command-list">{navigation.filter(n=>n[0].toLowerCase().includes(search.toLowerCase())).map(([name,to])=><Link key={to} to={to} onClick={()=>setPalette(false)}>{name}<ArrowUpRight aria-hidden="true"/></Link>)}</div></DialogContent></Dialog>
<Dialog open={mobile} onOpenChange={setMobile}><DialogContent className="mobile-sheet translate-x-0 translate-y-0"><DialogTitle><Wordmark/></DialogTitle><DialogDescription>Operations workspace</DialogDescription><nav className="mobile-nav" aria-label="Mobile Navigation">{nav(true)}</nav></DialogContent></Dialog></div>}