/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/fees': typeof FeesRoute
  '/identity': typeof IdentityRoute
  '/launch': typeof LaunchRoute
  '/pools': typeof PoolsRoute
  '/positions': typeof PositionsRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/fees': typeof FeesRoute
  '/identity': typeof IdentityRoute
  '/launch': typeof LaunchRoute
  '/pools': typeof PoolsRoute
  '/positions': typeof PositionsRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/fees': typeof FeesRoute
  '/identity': typeof IdentityRoute
  '/launch': typeof LaunchRoute
  '/pools': typeof PoolsRoute
  '/positions': typeof PositionsRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agent'
    | '/fees'
    | '/identity'
    | '/launch'
    | '/pools'
    | '/positions'
    | '/settings'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agent'
    | '/fees'
    | '/identity'
    | '/launch'
    | '/pools'
    | '/positions'
    | '/settings'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agent'
    | '/fees'
    | '/identity'
    | '/launch'
    | '/pools'
    | '/positions'
    | '/settings'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentRoute: typeof AgentRoute
  FeesRoute: typeof FeesRoute
  IdentityRoute: typeof IdentityRoute
  LaunchRoute: typeof LaunchRoute
  PoolsRoute: typeof PoolsRoute
  PositionsRoute: typeof PositionsRoute
  SettingsRoute: typeof SettingsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentRoute: AgentRoute,
  FeesRoute: FeesRoute,
  IdentityRoute: IdentityRoute,
  LaunchRoute: LaunchRoute,
  PoolsRoute: PoolsRoute,
  PositionsRoute: PositionsRoute,
  SettingsRoute: SettingsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}